services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - 8080:8000
    volumes:
      - ./env/local_save:/app/local_save
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "vk-pg"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - ./env/db:/var/lib/postgresql/data

  worker:
     build:
       context: .
       dockerfile: ./Dockerfile.worker
     depends_on:
       - db
       - backend
       - redis
     volumes:
       - ./env/local_save:/app/local_save

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    ports:
      - 8888:8888
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./env/local_save:/app/local_save
    links:
      - backend
