"""empty message

Revision ID: 22f0e09fad1e
Revises: 071457ecc515
Create Date: 2024-07-17 11:25:16.012367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f0e09fad1e'
down_revision: Union[str, None] = '071457ecc515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('processing', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'processing')
    # ### end Alembic commands ###
