"""Changed description for tag

Revision ID: 246111500312
Revises: c395557cebfa
Create Date: 2024-07-12 21:04:31.418680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '246111500312'
down_revision: Union[str, None] = 'c395557cebfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'description',
               existing_type=postgresql.ENUM('Silent', name='tagdescription'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'description',
               existing_type=sa.String(),
               type_=postgresql.ENUM('Silent', name='tagdescription'),
               existing_nullable=False)
    # ### end Alembic commands ###
