"""Add calculated soundwave

Revision ID: 4f6d27612391
Revises: d4652134d504
Create Date: 2024-07-09 09:20:36.907056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6d27612391'
down_revision: Union[str, None] = 'd4652134d504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('soundwave', sa.String(), nullable=False))
    op.add_column('result', sa.Column('soundwave', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'soundwave')
    op.drop_column('recordings', 'soundwave')
    # ### end Alembic commands ###
