"""Daite negra v moy anal

Revision ID: c395557cebfa
Revises: 7176a2d6f3a9
Create Date: 2024-07-12 07:15:38.905265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c395557cebfa'
down_revision: Union[str, None] = '7176a2d6f3a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('processing', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'processing')
    # ### end Alembic commands ###
