"""Add duration for recordings and results

Revision ID: d4652134d504
Revises: 37a962073526
Create Date: 2024-07-09 08:47:19.711595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4652134d504'
down_revision: Union[str, None] = '37a962073526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('result', sa.Column('duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'duration')
    op.drop_column('recordings', 'duration')
    # ### end Alembic commands ###
